/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness para el healthCheck del task de ECS.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet */
        get: operations["get_wallet_api_v1_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_wallet_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_v1_admin_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_v1_admin_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_v1_admin_teams__team_id__get"];
        put?: never;
        post?: never;
        /** Delete Team */
        delete: operations["delete_team_api_v1_admin_teams__team_id__delete"];
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_api_v1_admin_teams__team_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/teams/{team_id}/odds-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Odds Preview */
        get: operations["team_odds_preview_api_v1_admin_teams__team_id__odds_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_v1_admin_seasons_get"];
        put?: never;
        /** Create Season */
        post: operations["create_season_api_v1_admin_seasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/seasons/{season_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season */
        get: operations["get_season_api_v1_admin_seasons__season_id__get"];
        put?: never;
        post?: never;
        /** Delete Season */
        delete: operations["delete_season_api_v1_admin_seasons__season_id__delete"];
        options?: never;
        head?: never;
        /** Update Season */
        patch: operations["update_season_api_v1_admin_seasons__season_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/seasons/{season_id}/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Scoring Config */
        patch: operations["update_scoring_config_api_v1_admin_seasons__season_id__scoring_patch"];
        trace?: never;
    };
    "/api/v1/admin/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rounds */
        get: operations["list_rounds_api_v1_admin_rounds_get"];
        put?: never;
        /** Create Round */
        post: operations["create_round_api_v1_admin_rounds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rounds/{round_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round */
        get: operations["get_round_api_v1_admin_rounds__round_id__get"];
        put?: never;
        post?: never;
        /** Delete Round */
        delete: operations["delete_round_api_v1_admin_rounds__round_id__delete"];
        options?: never;
        head?: never;
        /** Update Round */
        patch: operations["update_round_api_v1_admin_rounds__round_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_v1_admin_matches_get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_api_v1_admin_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_api_v1_admin_matches__match_id__get"];
        put?: never;
        post?: never;
        /** Delete Match */
        delete: operations["delete_match_api_v1_admin_matches__match_id__delete"];
        options?: never;
        head?: never;
        /** Update Match */
        patch: operations["update_match_api_v1_admin_matches__match_id__patch"];
        trace?: never;
    };
    "/api/v1/matches/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Upcoming Matches */
        get: operations["list_upcoming_matches_api_v1_matches_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Prediction */
        put: operations["upsert_prediction_api_v1_matches__match_id__prediction_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place Bet */
        post: operations["place_bet_api_v1_matches__match_id__bets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/{round_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round Results */
        get: operations["get_round_results_api_v1_rounds__round_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Bets */
        get: operations["list_my_bets_api_v1_bets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Seasons
         * @description Lectura publica del catalogo de temporadas: el leaderboard necesita un id.
         */
        get: operations["list_seasons_api_v1_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seasons/{season_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_api_v1_seasons__season_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record Result */
        put: operations["record_result_api_v1_admin_matches__match_id__result_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/matches/{match_id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Settle Match */
        post: operations["settle_match_api_v1_admin_matches__match_id__settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/matches/{match_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Match */
        post: operations["cancel_match_api_v1_admin_matches__match_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BetCreate */
        BetCreate: {
            /** Selection */
            selection: components["schemas"]["OutcomeSelection"] | components["schemas"]["GoalBandSelection"];
            /** Stake */
            stake: number | string;
        };
        /**
         * BetMarket
         * @enum {string}
         */
        BetMarket: "OUTCOME" | "GOAL_BAND";
        /**
         * BetMatchRead
         * @description Contexto del partido que acompana a cada apuesta del historial.
         */
        BetMatchRead: {
            /** Home Team Name */
            home_team_name: string;
            /** Away Team Name */
            away_team_name: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
        };
        /** BetRead */
        BetRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            market: components["schemas"]["BetMarket"];
            /** Selection */
            selection: {
                [key: string]: unknown;
            };
            /** Stake */
            stake: string;
            /** Odds Snapshot */
            odds_snapshot: string;
            status: components["schemas"]["BetStatus"];
            /** Settled At */
            settled_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BetStatus
         * @enum {string}
         */
        BetStatus: "PENDING" | "WON" | "LOST" | "VOID";
        /** BetWithMatchRead */
        BetWithMatchRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            market: components["schemas"]["BetMarket"];
            /** Selection */
            selection: {
                [key: string]: unknown;
            };
            /** Stake */
            stake: string;
            /** Odds Snapshot */
            odds_snapshot: string;
            status: components["schemas"]["BetStatus"];
            /** Settled At */
            settled_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            match: components["schemas"]["BetMatchRead"];
        };
        /**
         * CreditTransactionKind
         * @enum {string}
         */
        CreditTransactionKind: "SEED" | "STAKE" | "PAYOUT" | "REFUND";
        /** CreditTransactionOut */
        CreditTransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["CreditTransactionKind"];
            /** Amount */
            amount: string;
            /** Bet Id */
            bet_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CreditTransactionPage */
        CreditTransactionPage: {
            /** Items */
            items: components["schemas"]["CreditTransactionOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * GoalBand
         * @enum {string}
         */
        GoalBand: "0-15" | "16-30" | "31-45" | "46-60" | "61-75" | "76-90+";
        /** GoalBandSelection */
        GoalBandSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            market: "GOAL_BAND";
            band: components["schemas"]["GoalBand"];
            /** Team Id */
            team_id?: string | null;
        };
        /** GoalIn */
        GoalIn: {
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Minute */
            minute: number;
            /**
             * Is Stoppage
             * @default false
             */
            is_stoppage: boolean;
        };
        /** GoalRead */
        GoalRead: {
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Minute */
            minute: number;
            /** Is Stoppage */
            is_stoppage: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardEntryRead */
        LeaderboardEntryRead: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Points */
            points: number;
            /** Exact Scores */
            exact_scores: number;
            /** Balance */
            balance: string;
        };
        /** MatchCreate */
        MatchCreate: {
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
        };
        /** MatchRead */
        MatchRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Settled At */
            settled_at: string | null;
        };
        /** MatchResultRead */
        MatchResultRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
            status: components["schemas"]["MatchStatus"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Goals */
            goals: components["schemas"]["GoalRead"][];
        };
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "SCHEDULED" | "FINISHED" | "CANCELLED";
        /** MatchUpcomingRead */
        MatchUpcomingRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
            /** Home Team Name */
            home_team_name: string;
            /** Away Team Name */
            away_team_name: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Odds Home */
            odds_home: string;
            /** Odds Draw */
            odds_draw: string;
            /** Odds Away */
            odds_away: string;
            /** Goal Band Odds */
            goal_band_odds: {
                [key: string]: string;
            };
            my_prediction: components["schemas"]["PredictionRead"] | null;
            /** My Bets */
            my_bets: components["schemas"]["BetRead"][];
        };
        /** MatchUpdate */
        MatchUpdate: {
            /** Round Id */
            round_id?: string | null;
            /** Home Team Id */
            home_team_id?: string | null;
            /** Away Team Id */
            away_team_id?: string | null;
            /** Kickoff At */
            kickoff_at?: string | null;
            status?: components["schemas"]["MatchStatus"] | null;
        };
        /** OddsPreview */
        OddsPreview: {
            /** Odds Home */
            odds_home: string;
            /** Odds Draw */
            odds_draw: string;
            /** Odds Away */
            odds_away: string;
        };
        /** OutcomeSelection */
        OutcomeSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            market: "OUTCOME";
            /**
             * Pick
             * @enum {string}
             */
            pick: "HOME" | "DRAW" | "AWAY";
        };
        /** PredictionIn */
        PredictionIn: {
            /** Predicted Home Score */
            predicted_home_score: number;
            /** Predicted Away Score */
            predicted_away_score: number;
        };
        /** PredictionRead */
        PredictionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Predicted Home Score */
            predicted_home_score: number;
            /** Predicted Away Score */
            predicted_away_score: number;
            /** Points Awarded */
            points_awarded: number | null;
        };
        /** ResultIn */
        ResultIn: {
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /**
             * Goals
             * @default []
             */
            goals: components["schemas"]["GoalIn"][];
        };
        /** RoundCreate */
        RoundCreate: {
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
            /** Number */
            number: number;
            /** Name */
            name: string;
            /**
             * Opens At
             * Format: date-time
             */
            opens_at: string;
            /**
             * Closes At
             * Format: date-time
             */
            closes_at: string;
        };
        /** RoundRead */
        RoundRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Season Id
             * Format: uuid
             */
            season_id: string;
            /** Number */
            number: number;
            /** Name */
            name: string;
            /**
             * Opens At
             * Format: date-time
             */
            opens_at: string;
            /**
             * Closes At
             * Format: date-time
             */
            closes_at: string;
        };
        /** RoundUpdate */
        RoundUpdate: {
            /** Number */
            number?: number | null;
            /** Name */
            name?: string | null;
            /** Opens At */
            opens_at?: string | null;
            /** Closes At */
            closes_at?: string | null;
        };
        /**
         * ScoringConfigUpdate
         * @description Partial update, merged key-by-key against DEFAULT_SCORING_RULES / DEFAULT_GOAL_BAND_ODDS.
         */
        ScoringConfigUpdate: {
            /** Outcome */
            outcome?: number | null;
            /** Exact Score */
            exact_score?: number | null;
            /** Goal Band */
            goal_band?: number | null;
            /** Goal Band Odds */
            goal_band_odds?: {
                [key: string]: number | string;
            } | null;
        };
        /** SeasonCreate */
        SeasonCreate: {
            /** Name */
            name: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Scoring Config */
            scoring_config?: {
                [key: string]: unknown;
            } | null;
        };
        /** SeasonRead */
        SeasonRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Scoring Config */
            scoring_config: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
        };
        /** SeasonSummaryRead */
        SeasonSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
        };
        /** SeasonUpdate */
        SeasonUpdate: {
            /** Name */
            name?: string | null;
            /** Starts On */
            starts_on?: string | null;
            /** Ends On */
            ends_on?: string | null;
            /** Status */
            status?: string | null;
        };
        /** TeamCreate */
        TeamCreate: {
            /** Name */
            name: string;
            /** Strength */
            strength: number;
            /** Crest Url */
            crest_url?: string | null;
        };
        /** TeamRead */
        TeamRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Strength */
            strength: number;
            /** Crest Url */
            crest_url: string | null;
        };
        /** TeamUpdate */
        TeamUpdate: {
            /** Name */
            name?: string | null;
            /** Strength */
            strength?: number | null;
            /** Crest Url */
            crest_url?: string | null;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserLogin */
        UserLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Phone */
            phone: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserRegister */
        UserRegister: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /** Phone */
            phone?: string | null;
            /** Contact Email */
            contact_email?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Contact Email */
            contact_email?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WalletBalanceOut */
        WalletBalanceOut: {
            /** Balance */
            balance: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    patch_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallet_api_v1_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletBalanceOut"];
                };
            };
        };
    };
    list_transactions_api_v1_wallet_transactions_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditTransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_v1_admin_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"][];
                };
            };
        };
    };
    create_team_api_v1_admin_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_api_v1_admin_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_api_v1_admin_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_api_v1_admin_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_odds_preview_api_v1_admin_teams__team_id__odds_preview_get: {
        parameters: {
            query: {
                opponent_strength: number;
                strength?: number | null;
            };
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seasons_api_v1_admin_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"][];
                };
            };
        };
    };
    create_season_api_v1_admin_seasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_api_v1_admin_seasons__season_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_season_api_v1_admin_seasons__season_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_season_api_v1_admin_seasons__season_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scoring_config_api_v1_admin_seasons__season_id__scoring_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rounds_api_v1_admin_rounds_get: {
        parameters: {
            query?: {
                season_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_round_api_v1_admin_rounds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_api_v1_admin_rounds__round_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_round_api_v1_admin_rounds__round_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_round_api_v1_admin_rounds__round_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_v1_admin_matches_get: {
        parameters: {
            query?: {
                round_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_v1_admin_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_admin_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_api_v1_admin_matches__match_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_api_v1_admin_matches__match_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upcoming_matches_api_v1_matches_upcoming_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchUpcomingRead"][];
                };
            };
        };
    };
    upsert_prediction_api_v1_matches__match_id__prediction_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_bet_api_v1_matches__match_id__bets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_results_api_v1_rounds__round_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResultRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_bets_api_v1_bets_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["BetStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetWithMatchRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seasons_api_v1_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummaryRead"][];
                };
            };
        };
    };
    get_leaderboard_api_v1_seasons__season_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_result_api_v1_admin_matches__match_id__result_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settle_match_api_v1_admin_matches__match_id__settle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_match_api_v1_admin_matches__match_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
